import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().int().positive().default(4000),
  API_BASE_URL: z.string().url().default("http://localhost:4000"),
  APP_NAME: z.string().default("ChowCall API"),
  CORS_ORIGINS: z.string().default("http://localhost:3000"),
  CORS_CREDENTIALS: z.coerce.boolean().default(true),
  CORS_METHODS: z.string().default("GET,POST,PUT,PATCH,DELETE,OPTIONS"),
  MONGODB_URI: z.string().min(1),
  MONGODB_DB_NAME: z.string().default("chowcall"),
  REDIS_URL: z.string().default("redis://127.0.0.1:6379"),
  REDIS_PREFIX: z.string().default("chowcall"),
  JWT_ACCESS_SECRET: z.string().min(12),
  JWT_REFRESH_SECRET: z.string().min(12),
  JWT_ACCESS_TTL: z.string().default("15m"),
  JWT_REFRESH_TTL: z.string().default("30d"),
  SWAGGER_ENABLED: z.coerce.boolean().default(true),
  SWAGGER_PATH: z.string().default("/docs"),
  PAYSTACK_SECRET_KEY: z.string().optional().default(""),
  PAYSTACK_PUBLIC_KEY: z.string().optional().default(""),
  PAYSTACK_WEBHOOK_SECRET: z.string().optional().default(""),
  PAYMENT_PROVIDER: z.enum(["paystack", "flutterwave"]).default("paystack"),
  BACKEND_BASE_URL: z.string().url().default("http://localhost:4000"),
  FLUTTERWAVE_SECRET_KEY: z.string().optional().default(""),
  FLUTTERWAVE_PUBLIC_KEY: z.string().optional().default(""),
  FLUTTERWAVE_WEBHOOK_SECRET: z.string().optional().default(""),
  MAPS_PROVIDER: z.enum(["mapbox"]).default("mapbox"),
  MAPBOX_ACCESS_TOKEN: z.string().min(1),
  LIVE_VOICE_PROVIDER: z.enum(["aws_nova_sonic", "azure_voice_live"]).default("aws_nova_sonic"),
  AWS_REGION: z.string().default("us-east-1"),
  AWS_ACCESS_KEY_ID: z.string().optional().default(""),
  AWS_SECRET_ACCESS_KEY: z.string().optional().default(""),
  AWS_SESSION_TOKEN: z.string().optional().default(""),
  AWS_BEARER_TOKEN_BEDROCK: z.string().optional().default(""),
  BEDROCK_SONIC_MODEL_ID: z.string().default("amazon.nova-sonic-v1:0"),
  DEFAULT_SONIC_LANGUAGE: z.string().default("en-US"),
  DEFAULT_SONIC_VOICE_ID: z.string().default("tiffany"),
  AZURE_VOICELIVE_ENDPOINT: z.string().url().optional().default("https://eastus.api.cognitive.microsoft.com/"),
  AZURE_VOICELIVE_API_KEY: z.string().optional().default(""),
  AZURE_EXISTING_AGENT_NAME: z.string().default("Chowcall"),
  AZURE_EXISTING_AGENT_VERSION: z.string().default("2"),
  AZURE_ENV_NAME: z.string().optional().default(""),
  AZURE_LOCATION: z.string().optional().default("eastus"),
  AZURE_SUBSCRIPTION_ID: z.string().optional().default(""),
  AZURE_EXISTING_AIPROJECT_ENDPOINT: z.string().url().optional().default("https://example.services.ai.azure.com/api/projects/example"),
  AZURE_EXISTING_RESOURCE_ID: z.string().optional().default(""),
  AZD_ALLOW_NON_EMPTY_FOLDER: z.coerce.boolean().optional().default(true),
  AZURE_AI_ENDPOINT: z.string().url().optional().default("https://example.services.ai.azure.com/api/projects/example"),
  AZURE_PROJECT_NAME: z.string().optional().default(""),
  AZURE_AI_RESOURCE_NAME: z.string().optional().default(""),
  AZURE_AI_FOUNDRY_API_KEY: z.string().optional().default(""),
  AZURE_AI_FOUNDRY_TARGET_URI: z.string().url().optional().default("https://example.services.ai.azure.com"),
  OPENAI_API_KEY: z.string().optional().default(""),
  AZURE_OPENAI_ENDPOINT: z.string().url().optional().default("https://example.openai.azure.com/"),
  AZURE_OPENAI_API_KEY: z.string().optional().default(""),
  AZURE_OPENAI_DEPLOYMENT_NAME: z.string().optional().default(""),
  AZURE_OPENAI_MODEL_NAME: z.string().optional().default(""),
  AZURE_OPENAI_API_VERSION: z.string().optional().default("2024-04-01-preview"),
  AZURE_SPEECH_ENDPOINT: z.string().url().optional().default("https://eastus.api.cognitive.microsoft.com/"),
  AZURE_SPEECH_KEY: z.string().optional().default(""),
  AZURE_SPEECH_REGION: z.string().optional().default(""),
  BREVO_API_KEY: z.string().optional().default(""),
  TWILIO_VOICE_WEBHOOK_URL: z.string().url().optional().default("http://localhost:4000/v1/voice/incoming"),
  TWILIO_STATUS_CALLBACK_URL: z.string().url().optional().default("http://localhost:4000/v1/voice/status"),
  TWILIO_MEDIA_STREAM_URL: z.string().optional().default(""),
  TWILIO_ACCOUNT_SID: z.string().optional().default(""),
  TWILIO_AUTH_TOKEN: z.string().optional().default(""),
  TWILIO_FROM_NUMBER: z.string().optional().default(""),
  VOICE_MODE: z.enum(["gather", "media_stream"]).default("gather"),
  EMAIL_PROVIDER: z.enum(["brevo"]).default("brevo"),
  EMAIL_FROM: z.string().default("ChowCall <hello@chowcall.ng>"),
  EMAIL_REPLY_TO: z.string().optional().default(""),
  BRAND_LOGO_URL: z.string().url().default("https://chowcall.ng/chowcall-logo.svg"),
  FRONTEND_BASE_URL: z.string().url().default("http://localhost:3000"),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(60000),
  RATE_LIMIT_MAX: z.coerce.number().int().positive().default(120),
  ENCRYPTION_KEY: z.string().min(12),
  QUEUE_CONCURRENCY: z.coerce.number().int().positive().default(5),
  PAYMENT_EXPIRY_MINUTES: z.coerce.number().int().positive().default(15),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  console.error("Invalid ChowCall backend environment");
  console.error(parsed.error.flatten().fieldErrors);
  process.exit(1);
}

export const env = {
  ...parsed.data,
  CORS_ORIGINS_LIST: parsed.data.CORS_ORIGINS.split(",").map((origin) => origin.trim()),
  CORS_METHODS_LIST: parsed.data.CORS_METHODS.split(",").map((method) => method.trim()),
};
