import { Router } from "express";
import { authRouter } from "./auth/auth.routes.js";
import { healthRouter } from "./health/health.routes.js";
import { tenantRouter } from "./tenants/tenant.routes.js";
import { userRouter } from "./users/user.routes.js";
import { staffRouter } from "./staff/staff.routes.js";
import { menuRouter } from "./menu/menu.routes.js";
import { inventoryRouter } from "./inventory/inventory.routes.js";
import { deliveryPricingRouter } from "./delivery-pricing/delivery-pricing.routes.js";
import { serviceFeesRouter } from "./service-fees/service-fees.routes.js";
import { pricingRouter } from "./pricing/pricing.routes.js";
import { orderRouter } from "./orders/order.routes.js";
import { paymentRouter } from "./payments/payment.routes.js";
import { callRouter } from "./calls/call.routes.js";
import { voiceRouter } from "./voice/voice.routes.js";
import { notificationRouter } from "./notifications/notification.routes.js";
import { mapRouter } from "./maps/map.routes.js";
import { analyticsRouter } from "./analytics/analytics.routes.js";
import { billingRouter } from "./billing/billing.routes.js";
import { escalationRouter } from "./escalations/escalation.routes.js";
import { publicOrderingRouter } from "./public-ordering/public-ordering.routes.js";
import { onboardingRouter } from "./onboarding/onboarding.routes.js";
import { planRouter } from "./plans/plan.routes.js";
import { subscriptionRouter } from "./subscriptions/subscription.routes.js";

export const v1Router = Router();

v1Router.use("/health", healthRouter);
v1Router.use("/auth", authRouter);
v1Router.use("/users", userRouter);
v1Router.use("/tenants", tenantRouter);
v1Router.use("/staff", staffRouter);
v1Router.use("/menu", menuRouter);
v1Router.use("/inventory", inventoryRouter);
v1Router.use("/delivery-pricing", deliveryPricingRouter);
v1Router.use("/service-fees", serviceFeesRouter);
v1Router.use("/pricing", pricingRouter);
v1Router.use("/orders", orderRouter);
v1Router.use("/payments", paymentRouter);
v1Router.use("/calls", callRouter);
v1Router.use("/voice", voiceRouter);
v1Router.use("/notifications", notificationRouter);
v1Router.use("/maps", mapRouter);
v1Router.use("/analytics", analyticsRouter);
v1Router.use("/billing", billingRouter);
v1Router.use("/escalations", escalationRouter);
v1Router.use("/public-ordering", publicOrderingRouter);
v1Router.use("/onboarding", onboardingRouter);
v1Router.use("/plans", planRouter);
v1Router.use("/subscriptions", subscriptionRouter);
